name: gaze_tts_app
description: Front camera gaze-to-TTS with SOS and a11y
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  camera: ^0.11.2
  flutter_tts: ^3.8.3
  vibration: ^3.1.4
  url_launcher: ^6.3.0
  permission_handler: ^12.0.1
  shared_preferences: ^2.3.2
  sqflite: ^2.3.3
  path: ^1.9.0
  intl: ^0.19.0
  tflite_flutter: ^0.10.4
  google_mlkit_face_detection: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/boards/cards_default.json
    - l10n/intl_ko.arb
    - l10n/intl_en.arb
